Build using nix
AShepelevv/astro.notebook pull request #232
Opened 2024-11-28 20:05 UTC by WeetHet

Adds flake.nix and a Dockerfile using it to either build locally using [nix](https://nixos.org) or using docker, which essentially downloads nixos and runs the same build process. The download size is much smaller than the full texlive as only needed packages are downloaded. They are defined in nix/texlive.nix and should be enough to install even outside of nix environment.

This also adds a devshell that you can enter using `nix develop` to get an environment with texlive with needed packages

2024-11-28 20:19 UTC, vobolgus commented on nix/texlive.nix
> +      wrapfig
wrapfig -> layout

2024-11-28 20:21 UTC, WeetHet commented on nix/texlive.nix
> +      wrapfig
done

2024-11-28 20:22 UTC, vobolgus submitted a review, later dismissed
Всё окей, и в плане сборки и в плане логики внутри кода

2025-07-12 21:28 UTC, AShepelevv requested changes

2025-08-21 14:08 UTC, vobolgus approved these changes

2025-08-21 16:32 UTC, AShepelevv approved these changes

2025-08-21 16:33 UTC, merged